filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ingest_data/*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: "message"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: json

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
